- Prenez le fichier "Data\eleves.csv" pour récupérer la liste des élèves
- Selectionnez tous les garçons dont le nom est "Fontaine"
- Sauvegardez le résultat dans un fichier de sortie au format CSV

In [6]:
import pandas as pd

In [7]:
chemin_abosolu = r"D:\Users\amine\Documents\GitHub\Python.Bureautique\Notebooks\Data\eleves.csv"
chemin_relatif = r"Data\eleves.csv"

In [9]:
df_eleves = pd.read_csv(chemin_abosolu, encoding="latin1")
df_eleves

        id   prenom       nom    sexe date_naissance  classe
0        1  Gabriel     Morin  Garçon     2007-10-04       3
1        2      Léa    Benoit   Fille     2005-12-30       1
2        3    Tiago     Morel  Garçon     2008-10-31       4
3        4     Emma       Roy   Fille     2011-06-04       6
4        5   Louise   Lacroix   Fille     2005-09-08       1
...    ...      ...       ...     ...            ...     ...
4995  4996      Tom    Bonnet  Garçon     2010-04-22       6
4996  4997    Chloé    Moreau   Fille     2011-09-18       7
4997  4998  Margaux     Henry   Fille     2006-11-05       2
4998  4999     Mila  Fontaine   Fille     2006-03-09       2
4999  5000     Nina  Martinez   Fille     2007-10-26       3

[5000 rows x 6 columns]

In [10]:
type(df_eleves)

pandas.core.frame.DataFrame

In [11]:
df_selection = df_eleves[(df_eleves["nom"] == "Fontaine") & (df_eleves["sexe"] == "Garçon")]
df_selection

        id    prenom       nom    sexe date_naissance  classe
183    184     Imran  Fontaine  Garçon     2006-12-19       2
296    297      Milo  Fontaine  Garçon     2008-01-09       3
303    304    Eliott  Fontaine  Garçon     2012-05-07       7
457    458     Timéo  Fontaine  Garçon     2005-02-10       1
497    498   Gaspard  Fontaine  Garçon     2007-07-28       3
932    933     Isaac  Fontaine  Garçon     2009-01-09       4
936    937  Valentin  Fontaine  Garçon     2012-05-20       7
1181  1182      Paul  Fontaine  Garçon     2008-10-23       4
1375  1376      Hugo  Fontaine  Garçon     2008-03-07       4
1485  1486      Amir  Fontaine  Garçon     2006-03-23       2
1526  1527    Marius  Fontaine  Garçon     2011-04-16       6
1547  1548    Arthur  Fontaine  Garçon     2006-02-26       2
1666  1667      Milo  Fontaine  Garçon     2011-02-08       6
1714  1715   Marceau  Fontaine  Garçon     2010-01-10       5
1758  1759    Eliott  Fontaine  Garçon     2007-12-19       3
2223  2224      Amir  Fontaine  Garçon     2012-05-20       7
2267  2268     Isaac  Fontaine  Garçon     2011-08-07       7
2309  2310  Valentin  Fontaine  Garçon     2005-09-07       1
2494  2495      Adam  Fontaine  Garçon     2010-09-27       6
2550  2551       Léo  Fontaine  Garçon     2009-08-17       5
2622  2623      Lyam  Fontaine  Garçon     2006-11-23       2
2655  2656       Tom  Fontaine  Garçon     2008-06-17       4
2723  2724   Mohamed  Fontaine  Garçon     2005-10-26       1
3159  3160     Rayan  Fontaine  Garçon     2008-01-06       3
3277  3278      Eden  Fontaine  Garçon     2007-03-24       3
3552  3553     Robin  Fontaine  Garçon     2008-05-06       3
3679  3680     Imran  Fontaine  Garçon     2008-12-13       4
3745  3746      Malo  Fontaine  Garçon     2010-07-18       6
3773  3774  Augustin  Fontaine  Garçon     2007-12-20       3
3970  3971      Axel  Fontaine  Garçon     2012-04-21       7
4078  4079      Maël  Fontaine  Garçon     2010-04-27       5
4312  4313  Valentin  Fontaine  Garçon     2009-05-02       5
4662  4663   Gaspard  Fontaine  Garçon     2007-04-16       2

In [12]:
df_selection.to_csv("eleves_selection.csv", index=False)
print("Sauvegarde effectuée")

Sauvegarde effectuée