In [1]:
import pandas as pd

In [2]:
df_clients = pd.DataFrame({
    'client_id': [1, 2, 3, 4],
    'nom': ['Alice', 'Bob', 'Charlie', 'David'],
    'ville': ['Paris', 'Lyon', 'Marseille', 'Toulouse']
})

In [3]:
df_clients

   client_id      nom      ville
0          1    Alice      Paris
1          2      Bob       Lyon
2          3  Charlie  Marseille
3          4    David   Toulouse

In [10]:
noms_colonnes = list(df_clients.columns)
noms_colonnes.remove("nom")
noms_colonnes

['client_id', 'ville']

In [11]:
df_sortie = df_clients[noms_colonnes]
df_sortie

   client_id      ville
0          1      Paris
1          2       Lyon
2          3  Marseille
3          4   Toulouse